Repository UMC8-TeumTeum/FE, pull requests merged in 2025-07, with the labels that each got.

#3 [SETTING/#2] 공통 컴포넌트 세팅
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/drawable/ic_undo.xml
  gradle/libs.versions.toml
Labels: ⚙️setting, 🐰희원🐰

#6 [Feat/#4] 로그인01 화면 제작
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teumteum/SignIn/LoginActivity.kt
  app/src/main/java/com/example/teumteum/Splash/SplashActivity.kt
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_naver.xml
  app/src/main/res/drawable/ic_teumteum.xml
  app/src/main/res/drawable/rounded_btn_bg.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_splash.xml
  gradle/libs.versions.toml
Labels: ✨feature, 👽우진👽

#8 [Feat/#7] 회원가입(약관동의) 화면 제작
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teumteum/SignUp/AgreementFragment.kt
  app/src/main/java/com/example/teumteum/SignUp/CompleteFragment.kt
  app/src/main/java/com/example/teumteum/SignUp/SignUpActivity.kt
  app/src/main/java/com/example/teumteum/SignUp/TermsDetailFragment.kt
  app/src/main/res/drawable/rounded_border.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_agreement.xml
  app/src/main/res/layout/fragment_complete.xml
  app/src/main/res/layout/fragment_terms_detail.xml
  app/src/main/res/values/strings.xml
Labels: ✨feature, 👽우진👽

#13 [Feat/#9] 온보딩01 화면 제작 및 화면 이동 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teumteum/SignIn/LoginActivity.kt
  app/src/main/java/com/example/teumteum/SignUp/CompleteFragment.kt
  app/src/main/java/com/example/teumteum/SignUp/OnBoardingNicknameFragment.kt
  app/src/main/java/com/example/teumteum/SignUp/OnBoardingProfileFragment.kt
  app/src/main/java/com/example/teumteum/Splash/SplashActivity.kt
  app/src/main/res/drawable/camera_btn.png
  app/src/main/res/drawable/circle_bg.xml
  app/src/main/res/drawable/clear_btn.png
  app/src/main/res/drawable/rounded_edit_text.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_on_boarding_nickname.xml
  app/src/main/res/layout/fragment_on_boarding_profile.xml
Labels: ✨feature, 👽우진👽

#21 [Feat/#20] 온보딩02 화면 제작
  app/src/main/java/com/example/teumteum/data/Schedule.kt
  app/src/main/java/com/example/teumteum/ui/singup/BottomSheetScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/singup/OnBoardingProfileFragment.kt
  app/src/main/java/com/example/teumteum/ui/singup/OnBoardingScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/singup/ScheduleAdapter.kt
  app/src/main/res/drawable/bg_day_selected.xml
  app/src/main/res/drawable/ic_arrow_sv.xml
  app/src/main/res/drawable/ic_fab_add_purple_sv.xml
  app/src/main/res/layout/fragment_bottom_sheet_schedule.xml
  app/src/main/res/layout/fragment_on_boarding_schedule.xml
  app/src/main/res/layout/item_schedule.xml
Labels: ✨feature, 👽우진👽

#23 [FEAT/#17] 친구 5.2.2화면 ~ 5.2.2.3 화면 구현
  app/src/main/java/com/example/teumteum/ui/friend/Friend01SearchFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02AcceptBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02PossibleTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02SuggestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendSendFragment.kt
  app/src/main/res/drawable/friend_down.xml
  app/src/main/res/drawable/friend_temi.xml
  app/src/main/res/drawable/friend_time_card_bg_default.xml
  app/src/main/res/drawable/friend_time_card_bg_selected.xml
  app/src/main/res/drawable/friend_up.xml
  app/src/main/res/layout/dialog_time_picker.xml
  app/src/main/res/layout/fragment_friend01_search.xml
  app/src/main/res/layout/fragment_friend02_possible_time.xml
  app/src/main/res/layout/fragment_friend02_request.xml
  app/src/main/res/layout/fragment_friend02_suggest.xml
  app/src/main/res/layout/fragment_friend_send.xml
  app/src/main/res/layout/friend02_item_teum_card.xml
  app/src/main/res/values/themes.xml
Labels: ✨feature, 🐰희원🐰

#25 [FEAT/#22] 수면 패턴 등록 화면 구현
  app/src/main/java/com/example/teumteum/ui/singup/OnBoardingScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/singup/OnBoardingSleepPatternFragment.kt
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/rounded_sleep_pattern.xml
  app/src/main/res/layout/fragment_on_boarding_sleep_pattern.xml
Labels: ✨feature, 👽우진👽

#32 [Feat/#27] 온보딩04 페이지 제작
  app/src/main/java/com/example/teumteum/ui/singup/OnBoardingRemindFragment.kt
  app/src/main/java/com/example/teumteum/ui/singup/OnBoardingSleepPatternFragment.kt
  app/src/main/res/drawable/btn_remind_toggle_thumb.xml
  app/src/main/res/drawable/btn_remind_toggle_track.xml
  app/src/main/res/drawable/rounded_remind_bg.xml
  app/src/main/res/layout/fragment_on_boarding_remind.xml
  app/src/main/res/values/styles.xml
Labels: ✨feature, 👽우진👽

#30 [DOCS/#24] ~ 5.2.2.3 친구 UI 수정
  app/src/main/java/com/example/teumteum/ui/friend/Friend01SearchFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RejectBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RequestFragment.kt
  app/src/main/res/drawable/friend_search_edittext_bg.xml
  app/src/main/res/layout/bottom_sheet_friend02_accept.xml
  app/src/main/res/layout/bottom_sheet_friend02_reject.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/fragment_friend01_search.xml
  app/src/main/res/layout/fragment_friend02_possible_time.xml
  app/src/main/res/layout/fragment_friend02_request.xml
  app/src/main/res/layout/fragment_friend02_suggest.xml
  app/src/main/res/layout/friend01_item_following.xml
  app/src/main/res/layout/friend01_item_recommend_card.xml
  app/src/main/res/layout/friend02_item_teum_card.xml
Labels: 📝docs, 🐰희원🐰

#34 [#29] Feat: 위시리스트 조회 화면, 편집 화면 제작
  .gitignore
  app/.gitignore
  app/schemas/com.example.teumteum.data.local.AppDatabase/1.json
  app/src/main/java/com/example/teumteum/TodoAdapter.kt
  app/src/main/java/com/example/teumteum/data/entities/Wish.kt
  app/src/main/java/com/example/teumteum/ui/edit/WishEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/home/BottomSheetRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/home/CalendarVPAdapter.kt
  app/src/main/java/com/example/teumteum/ui/home/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/main/MainActivity.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoRVAdapter.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishOnlyBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistEditRVAdapter.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistRVAdapter.kt
  app/src/main/res/drawable/circle_purple.xml
  app/src/main/res/drawable/ic_back_arrow_sv.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/alarm_dropdown.xml
  app/src/main/res/layout/dialog_confirm_wish_delete.xml
  app/src/main/res/layout/dialog_confirm_wish_edit.xml
  app/src/main/res/layout/fragment_bottom_sheet_register.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_todo_edit.xml
  app/src/main/res/layout/fragment_todo_register.xml
  app/src/main/res/layout/fragment_wish_edit.xml
  app/src/main/res/layout/fragment_wish_register.xml
  app/src/main/res/layout/fragment_wishlist.xml
  app/src/main/res/layout/fragment_wishlist_edit.xml
  app/src/main/res/layout/item_alarm.xml
  app/src/main/res/layout/item_day_cell.xml
  app/src/main/res/layout/item_todolist.xml
  app/src/main/res/layout/item_wishlist.xml
  app/src/main/res/layout/item_wishlist_edit.xml
  app/src/main/res/values/colors.xml
Labels: ✨feature, 😺승현😺

#41 [Feat/#40] 마이페이지02 화면 제작
  app/src/main/java/com/example/teumteum/ui/myhome/MyAccountSettingFragment.kt
  app/src/main/java/com/example/teumteum/ui/myhome/MyAlarmSettingFragment.kt
  app/src/main/java/com/example/teumteum/ui/myhome/MyHomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/myhome/MySettingFragment.kt
  app/src/main/res/layout/fragment_my_account_setting.xml
  app/src/main/res/layout/fragment_my_alarm_setting.xml
  app/src/main/res/layout/fragment_my_setting.xml
Labels: ✨feature, 👽우진👽

#45 [FEAT/#31] < 5 *친구 > ~ < 5.2.3 재요청 보기 > UI 구현
  app/src/main/java/com/example/teumteum/ui/friend/Friend02ResponseFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendResponseCardAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendResponseData.kt
  app/src/main/res/drawable/friend02_bg_response_time.xml
  app/src/main/res/layout/fragment_friend02_response.xml
  app/src/main/res/layout/friend02_item_request_teum_card.xml
Labels: ✨feature, 🐰희원🐰

#51 [#50] Refactor: 투두 바텀시트 캘린더 적용 및 홈 화면 등 마진 조절
  app/src/main/java/com/example/teumteum/ui/calendar/MonthlyCalendarFragment.kt
  app/src/main/java/com/example/teumteum/ui/main/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoRegisterFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_todo_edit.xml
  app/src/main/res/layout/fragment_todo_register.xml
Labels: ♻️refactor, 😺승현😺

#53 [REFACTOR/#49] 피드백 및 전체적인 화면 수정
  app/src/main/java/com/example/teumteum/ui/friend/Friend02PossibleTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02SuggestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/res/layout/bottom_sheet_friend02_accept.xml
  app/src/main/res/layout/bottom_sheet_friend02_reject.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/fragment_friend01_search.xml
  app/src/main/res/layout/fragment_friend02_possible_time.xml
  app/src/main/res/layout/fragment_friend02_request.xml
  app/src/main/res/layout/fragment_friend02_response.xml
  app/src/main/res/layout/fragment_friend02_suggest.xml
  app/src/main/res/layout/friend02_item_request_teum_card.xml
  app/src/main/res/layout/friend02_item_teum_card.xml
Labels: ♻️refactor, 🐰희원🐰

#55 Feat/#54 friend profile
  app/src/main/java/com/example/teumteum/ui/friend/FollowingAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowingFragment.kt
  app/src/main/res/drawable/friend_profile_send.xml
  app/src/main/res/drawable/friend_profile_star.xml
  app/src/main/res/drawable/friend_setting.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/fragment_friend_profile_follow.xml
  app/src/main/res/layout/fragment_friend_profile_following.xml
  app/src/main/res/layout/friend01_item_following.xml
Labels: ✨feature, 🐰희원🐰

#58 [#52] Feat: 알림 화면 제작
  app/src/main/java/com/example/teumteum/data/entities/Alarm.kt
  app/src/main/java/com/example/teumteum/ui/alarm/AlarmFragment.kt
  app/src/main/java/com/example/teumteum/ui/alarm/AlarmRVAdapter.kt
  app/src/main/java/com/example/teumteum/ui/calendar/MonthlyCalendarFragment.kt
  app/src/main/java/com/example/teumteum/ui/calendar/WeeklyCalendarFragment.kt
  app/src/main/java/com/example/teumteum/ui/filling/FillingActivity02Fragment.kt
  app/src/main/java/com/example/teumteum/ui/main/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistFragment.kt
  app/src/main/java/com/example/teumteum/util/ViewShadowUtil.kt
  app/src/main/res/drawable/ic_fab_add_sv.xml
  app/src/main/res/drawable/ic_fab_refresh_sv.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_filling_activity_01.xml
  app/src/main/res/layout/fragment_filling_activity_02.xml
  app/src/main/res/layout/fragment_filling_setting_01.xml
  app/src/main/res/layout/fragment_filling_setting_02.xml
  app/src/main/res/layout/fragment_filling_setting_03.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_alarm.xml
  app/src/main/res/layout/fragment_monthly_calendar.xml
  app/src/main/res/layout/fragment_weekly_calendar.xml
  app/src/main/res/layout/fragment_wish_setting_01.xml
  app/src/main/res/layout/fragment_wish_setting_02.xml
  app/src/main/res/layout/fragment_wish_setting_03.xml
  app/src/main/res/layout/fragment_wishlist.xml
  app/src/main/res/layout/fragment_wishlist_edit.xml
  app/src/main/res/layout/item_home_alarm.xml
  app/src/main/res/layout/item_todolist.xml
  app/src/main/res/layout/item_wishlist.xml
  app/src/main/res/layout/item_wishlist_edit.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: ✨feature, 😺승현😺

#64 [FIX/#63] tools 선언 누락 문제 해결
  app/src/main/res/layout/fragment_todo_edit.xml
Labels: 🐛fix, 😺승현😺

#66 [REFACTOR/#56] 친구 UI 화면 수정
  app/src/main/res/layout/fragment_friend01_search.xml
  app/src/main/res/layout/fragment_friend02_possible_time.xml
  app/src/main/res/layout/fragment_friend02_request.xml
  app/src/main/res/layout/fragment_friend02_suggest.xml
  app/src/main/res/layout/fragment_friend_send.xml
Labels: ♻️refactor, 🐰희원🐰

#70 [Feat/#69] 위시리스트 조회 api 연동
  app/src/main/java/com/example/teumteum/data/entities/WishlistItem.kt
  app/src/main/java/com/example/teumteum/data/remote/WishRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/WishResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/WishRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/WishService.kt
  app/src/main/java/com/example/teumteum/data/remote/WishlistResult.kt
  app/src/main/java/com/example/teumteum/ui/main/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishView.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistRVAdapter.kt
Labels: ✨feature, 😺승현😺

#65 [Feat/#60] 원형 시간표 UI - 홈화면
  app/build.gradle.kts
  app/src/main/java/com/example/teumteum/data/TimeBlock.kt
  app/src/main/java/com/example/teumteum/data/TimeType.kt
  app/src/main/java/com/example/teumteum/ui/clock/ChartUtils.kt
  app/src/main/java/com/example/teumteum/ui/clock/IconPieChartRenderer.kt
  app/src/main/java/com/example/teumteum/ui/main/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishSetting01Fragment.kt
  app/src/main/res/drawable/clock_basic_center_sv.xml
  app/src/main/res/drawable/clock_basic_sv.xml
  app/src/main/res/drawable/clock_indicator_bar.xml
  app/src/main/res/drawable/clock_indicator_bar_purple.xml
  app/src/main/res/drawable/clock_indicator_dot.xml
  app/src/main/res/drawable/clock_mini_center_sv.xml
  app/src/main/res/drawable/clock_mini_sv.xml
  app/src/main/res/drawable/ic_sleep_sv.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_wish_setting_01.xml
  app/src/main/res/values/colors.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ✨feature, 👽우진👽

#74 [FEAT/#73] 위시 수정 api 연동
  app/src/main/java/com/example/teumteum/data/remote/wish/WishRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/wish/WishService.kt
  app/src/main/java/com/example/teumteum/data/remote/wish/dto/WishRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/wish/dto/WishResponse.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/view/EditWishView.kt
  app/src/main/java/com/example/teumteum/ui/wish/view/RegisterWishView.kt
  app/src/main/java/com/example/teumteum/ui/wish/view/WishlistView.kt
Labels: ✨feature, 😺승현😺

#86 [Refactor/#76] 온보딩 플로우 변경, UI 변경점
  app/src/main/java/com/example/teumteum/data/Schedule.kt
  app/src/main/java/com/example/teumteum/ui/signup/BottomSheetScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingProfileFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingSleepPatternFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/ScheduleAdapter.kt
  app/src/main/java/com/example/teumteum/utils/NetworkModule.kt
  app/src/main/res/drawable/signup_complete_image.xml
  app/src/main/res/layout/fragment_bottom_sheet_schedule.xml
  app/src/main/res/layout/fragment_complete.xml
  app/src/main/res/layout/fragment_on_boarding_sleep_pattern.xml
Labels: ♻️refactor, 👽우진👽

#90 [FEAT/#82] 5.5.4 틈메이트 매칭_세부 조절 + 완료 화면 구현
  app/src/main/java/com/example/teumteum/ui/friend/FriendMatchingPreviewDialog.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateMatchingDetailFragment.kt
  app/src/main/res/drawable/nextbtn.xml
  app/src/main/res/drawable/previousbtn.xml
  app/src/main/res/layout/dialog_friend_matching_preview.xml
Labels: ✨feature, 🐰희원🐰

#89 [Refactor/#85] 빈틈채우기 시간표 ui 작업
  app/src/main/java/com/example/teumteum/ui/filling/FillingSetting01Fragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoRegisterFragment.kt
  app/src/main/java/com/example/teumteum/utils/NetworkModule.kt
  app/src/main/res/layout/dialog_time_picker.xml
  app/src/main/res/layout/fragment_filling_setting_01.xml
  app/src/main/res/layout/fragment_filling_setting_02.xml
  app/src/main/res/layout/fragment_filling_setting_03.xml
  app/src/main/res/layout/fragment_wish_setting_01.xml
  app/src/main/res/layout/fragment_wish_setting_02.xml
  app/src/main/res/layout/fragment_wish_setting_03.xml
  app/src/main/res/layout/fragment_wishlist.xml
  app/src/main/res/layout/fragment_wishlist_edit.xml
Labels: ♻️refactor, 😺승현😺

#88 [Feat/#87] 약관동의 API 연동
  app/src/main/java/com/example/teumteum/data/remote/agreement/AgreementRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/agreement/AgreementService.kt
  app/src/main/java/com/example/teumteum/data/remote/agreement/dto/AgreementRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/agreement/dto/AgreementResponse.kt
  app/src/main/java/com/example/teumteum/ui/signup/AgreementFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/view/AgreementView.kt
Labels: ✨feature, 👽우진👽

#98 [Feat/#93] 온보딩 닉네임, 직종 입력 API 연동
  app/src/main/java/com/example/teumteum/data/remote/onboarding/OnBoardingRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/OnBoardingService.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/dto/NicknameJobRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/dto/NicknameJobResponse.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingNicknameFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/view/NicknameJobFieldView.kt
  app/src/main/res/layout/fragment_on_boarding_nickname.xml
Labels: ✨feature, 👽우진👽

#104 [Setting/#103] 서버주소, 토큰 관리
  app/build.gradle.kts
  app/src/main/java/com/example/teumteum/data/remote/onboarding/OnBoardingService.kt
  app/src/main/java/com/example/teumteum/utils/NetworkModule.kt
Labels: ♻️refactor, ⚙️setting, 👽우진👽

#107 [BUG#106] 투두 바텀시트 에러 코드 삭제
  app/src/main/res/layout/fragment_todo_edit.xml
  app/src/main/res/layout/fragment_todo_register.xml
Labels: 🐛fix, 😺승현😺

#100 [FEAT/#96] 5.5.3 틈메이트 매칭_시간 확인
  app/src/main/java/com/example/teumteum/ui/clock/ChartUtils.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateDateFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateFriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateMatchingDetailFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/FollowerAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/FriendProfileAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/data/FollowerData.kt
  app/src/main/java/com/example/teumteum/ui/friend/data/FriendProfileData.kt
  app/src/main/res/drawable/eyes_on.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/fragment_friend_roommate_date.xml
  app/src/main/res/layout/fragment_friend_roommate_friend.xml
  app/src/main/res/layout/fragment_friend_roommate_time.xml
  app/src/main/res/layout/friend01_item_follower.xml
  app/src/main/res/layout/item_friend_profile_card.xml
Labels: ✨feature, 🐰희원🐰
