Repository UMC8-TeumTeum/FE, pull requests merged in 2025-08, with the labels that each got.

#116 [FEAT/#115] 친구 사용자 찾기 API 연동
  app/build.gradle.kts
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/FriendSearchResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/FriendSearchService.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/search/FriendSearchRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/ui/friend/FollowUsuer.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend01SearchFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend01SearchResultFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/FollowingAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/SearchResultAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/data/FollowData.kt
  app/src/main/java/com/example/teumteum/ui/friend/view/FriendSearchView.kt
  app/src/main/res/layout/fragment_friend01_search_result.xml
  app/src/main/res/layout/item_search_user.xml
Labels: ✨feature, 🐰희원🐰

#117 [FEAT/#110] 친구 프로필 조회 API 연동
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/FriendProfileResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/FriendProfileService.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/profile/FriendProfileRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/view/FriendProfileView.kt
Labels: ✨feature, 🐰희원🐰

#120 [REFACTOR/#119] 사용자 검색 LOG 수정
  app/src/main/java/com/example/teumteum/ui/friend/Friend01SearchResultFragment.kt
Labels: ♻️refactor, 🐰희원🐰

#124 [FEAT/#122] 틈 요청 조회하기 API 연동
  app/build.gradle.kts
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/TeumReceivedResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/TeumReceivedService.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/TeumRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/TeumRequestService.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/TeumResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/teum/TeumReceivedRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/teum/TeumRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02PossibleTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RequestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02SuggestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRequestCardAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/RecommendAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/RecommendAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/TeumReceivedPagerAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/view/TeumReceivedView.kt
  app/src/main/java/com/example/teumteum/ui/friend/view/TeumRequestView.kt
  app/src/main/res/drawable/purple_teum.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/friend01_item_recommend_card.xml
  app/src/main/res/layout/friend02_item_teum_card.xml
Labels: ✨feature, 🐰희원🐰

#128 [BUG/#126] 위시 mvvm 구조 변경하면서 발생한 문제 해결
  app/src/main/java/com/example/teumteum/data/remote/wish/repository/WishRepository.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/viewModel/WishViewModel.kt
Labels: 🐛fix, 😺승현😺

#130 [Refactor/#129] 투두등록 mvvm 구조 변경
  app/src/main/java/com/example/teumteum/data/remote/activity/dto/ActivityWishResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/todo/TodoRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/todo/TodoService.kt
  app/src/main/java/com/example/teumteum/data/remote/todo/model/GetTodoResult.kt
  app/src/main/java/com/example/teumteum/data/remote/todo/model/TodoListResult.kt
  app/src/main/java/com/example/teumteum/data/remote/todo/model/TodoRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/todo/model/TodoResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/todo/model/TodoResult.kt
  app/src/main/java/com/example/teumteum/data/remote/todo/repository/TodoRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/todo/service/TodoService.kt
  app/src/main/java/com/example/teumteum/data/remote/wish/model/WishResponse.kt
  app/src/main/java/com/example/teumteum/ui/main/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/view/DeleteTodoView.kt
  app/src/main/java/com/example/teumteum/ui/todo/view/EditTodoView.kt
  app/src/main/java/com/example/teumteum/ui/todo/view/RegisterTodoView.kt
  app/src/main/java/com/example/teumteum/ui/todo/view/TodoListView.kt
  app/src/main/java/com/example/teumteum/ui/todo/view/TodoView.kt
  app/src/main/java/com/example/teumteum/ui/todo/viewModel/TodoViewModel.kt
  app/src/main/java/com/example/teumteum/utils/ApiModule.kt
Labels: ♻️refactor, 😺승현😺

#131 [REFACTOR/#127] 친구 mvvm 구조 변경
  app/src/main/java/com/example/teumteum/data/AppUserManager.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/FriendProfileService.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/FriendSearchResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/FriendSearchService.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/TeumReceivedService.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/TeumRequestService.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/dto/TeumResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/FriendProfileResult.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/FriendSearchResult.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/TeumReceivedResult.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/TeumRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/TeumRequestResult.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/profile/FriendProfileRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/repository/FriendRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/search/FriendSearchRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/service/FriendService.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/teum/TeumReceivedRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/teum/TeumRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend01SearchFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend01SearchResultFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RequestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowingFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRequestCardAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/RecommendAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/SearchResultAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/TeumReceivedPagerAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/data/FollowData.kt
  app/src/main/java/com/example/teumteum/ui/friend/view/FriendProfileView.kt
  app/src/main/java/com/example/teumteum/ui/friend/view/FriendSearchView.kt
  app/src/main/java/com/example/teumteum/ui/friend/view/TeumReceivedView.kt
  app/src/main/java/com/example/teumteum/ui/friend/view/TeumRequestView.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
  app/src/main/java/com/example/teumteum/utils/ApiModule.kt
Labels: ♻️refactor, 🐰희원🐰

#136 [FEAT/#132] 틈 응답 상태 변경 API 연동
  app/src/main/java/com/example/teumteum/data/remote/friend/model/TeumStatusRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/TeumStatusResult.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/repository/FriendRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/service/FriendService.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02AcceptBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02PossibleTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RejectBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RequestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02SuggestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
Labels: ✨feature, 🐰희원🐰

#134 [Refactor/#133] 온보딩 MVVM 구조로 리팩토링
  app/src/main/java/com/example/teumteum/data/remote/agreement/AgreementRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/agreement/AgreementService.kt
  app/src/main/java/com/example/teumteum/data/remote/agreement/dto/AgreementResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/OnBoardingRetrofitInterface.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/OnBoardingService.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/dto/PresignedResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/AgreementRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/NicknameJobRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/NicknameJobResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/PresignedRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/PresignedResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/ProfileImageRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/ProfileImageResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/ScheduleRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/ScheduleResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/SleepPatternRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/SleepPatternResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/repository/OnBoardingRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/service/OnBoardingService.kt
  app/src/main/java/com/example/teumteum/ui/signup/AgreementFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/BottomSheetScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/CompleteFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingNicknameFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingProfileFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingSleepPatternFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/ScheduleAdapter.kt
  app/src/main/java/com/example/teumteum/ui/signup/data/Schedule.kt
  app/src/main/java/com/example/teumteum/ui/signup/view/AgreementView.kt
  app/src/main/java/com/example/teumteum/ui/signup/view/NicknameJobFieldView.kt
  app/src/main/java/com/example/teumteum/ui/signup/view/ProfileImageView.kt
  app/src/main/java/com/example/teumteum/ui/signup/view/ScheduleView.kt
  app/src/main/java/com/example/teumteum/ui/signup/view/SleepPatternView.kt
  app/src/main/java/com/example/teumteum/ui/signup/viewModel/OnBoardingUiState.kt
  app/src/main/java/com/example/teumteum/ui/signup/viewModel/OnBoardingViewModel.kt
  app/src/main/java/com/example/teumteum/utils/ApiException.kt
  app/src/main/java/com/example/teumteum/utils/ApiModule.kt
  app/src/main/java/com/example/teumteum/utils/ApiResponseHandler.kt
Labels: ♻️refactor, 👽우진👽

#138 [Feat/#135] 온보딩 리마인드 알림 등록 API
  app/src/main/java/com/example/teumteum/data/remote/onboarding/model/RemindRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/repository/OnBoardingRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/onboarding/service/OnBoardingService.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingNicknameFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingProfileFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingRemindFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingSleepPatternFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/viewModel/OnBoardingViewModel.kt
Labels: ✨feature, 👽우진👽

#155 [Feat/#153] 틈 요청 읽기 처리 API 연동
  app/src/main/java/com/example/teumteum/data/remote/friend/repository/FriendRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/service/FriendService.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/RecommendAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
  app/src/main/res/drawable/bg_card_folded_corner.xml
  app/src/main/res/layout/friend01_item_recommend_card_read.xml
  app/src/main/res/values/styles.xml
Labels: ✨feature, 👽우진👽

#157 [Feat/#141] 틈 재요청 플로우 API 연동
  app/src/main/java/com/example/teumteum/data/remote/friend/model/PossibleTimeRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/PossibleTimeResult.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/ResendTeumRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/ResendTeumResult.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/repository/FriendRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/service/FriendService.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RequestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02SuggestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/TimeCardAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/data/TimeCardItem.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_friend02_suggest.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_time_card.xml
Labels: ✨feature, 👽우진👽

#163 [Feat/#154] 채움활동 ai추천 컨텐츠 불러오기
  app/build.gradle.kts
  app/src/main/java/com/example/teumteum/data/remote/activity/model/ActivityAiResult.kt
  app/src/main/java/com/example/teumteum/data/remote/activity/model/ActivityRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/activity/model/ActivityResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/activity/repository/ActivityRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/activity/service/ActivityService.kt
  app/src/main/java/com/example/teumteum/ui/activity/FillingActivity01Fragment.kt
  app/src/main/java/com/example/teumteum/ui/activity/FillingActivity02Fragment.kt
  app/src/main/java/com/example/teumteum/ui/activity/FillingSetting01Fragment.kt
  app/src/main/java/com/example/teumteum/ui/activity/LoadingPageFragment.kt
  app/src/main/java/com/example/teumteum/ui/activity/adapter/AiRecommendRVAdapter.kt
  app/src/main/java/com/example/teumteum/ui/activity/adapter/WishRecommendRVAdapter.kt
  app/src/main/java/com/example/teumteum/ui/activity/viewModel/ActivityViewModel.kt
  app/src/main/res/drawable/bg_skeleton_circle.xml
  app/src/main/res/drawable/bg_skeleton_rect.xml
  app/src/main/res/drawable/ic_temi_search.png
  app/src/main/res/layout/fragment_filling_activity_02.xml
  app/src/main/res/layout/fragment_loading_page.xml
  app/src/main/res/layout/item_skeleton_row.xml
  app/src/main/res/layout/item_wishlist.xml
  app/src/main/res/values/colors.xml
Labels: ✨feature, 😺승현😺

#164 [Feat/#162] 가능한 시간대 조회 및 틈 요청 API
  app/src/main/java/com/example/teumteum/data/remote/friend/repository/FriendRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/service/FriendService.kt
  app/src/main/java/com/example/teumteum/ui/clock/ChartUtils.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02SuggestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendMatchingPreviewDialog.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateDateFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateFriendAddFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateFriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateMatchingDetailFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/data/SelectedTime.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
  app/src/main/res/drawable/teumi_teuma_ball.png
  app/src/main/res/drawable/teumi_teuma_down.png
  app/src/main/res/drawable/teumi_teuma_eat.png
  app/src/main/res/drawable/teumi_teuma_juice.png
  app/src/main/res/layout/fragment_friend_roommate_matching_detail.xml
Labels: ✨feature, 👽우진👽

#167 [FIX/#166] 카카오 로그인 호출을 ViewModel에서 Activity로 이동
  app/src/main/java/com/example/teumteum/ui/signin/LoginActivity.kt
  app/src/main/java/com/example/teumteum/ui/signin/viewModel/LoginViewModel.kt
Labels: 🐛fix

#174 [FIX/#173] 투두 등록 시 성공 토스트 중복 노출 방지
  app/src/main/java/com/example/teumteum/ui/todo/TodoRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/viewModel/TodoViewModel.kt
Labels: 🐛fix

#177 [Fix/#175] 투두 삭제 시 시간표, 투두 리스트 최신화 문제
  app/src/main/java/com/example/teumteum/ui/clock/ChartUtils.kt
  app/src/main/java/com/example/teumteum/ui/main/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/main/viewModel/HomeViewModel.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoEditFragment.kt
Labels: 🐛fix, 👽우진👽

#181 [FIX/#180] 네트워크 모듈 구조 개선 및 토큰 재발급 로직 수정
  app/src/main/java/com/example/teumteum/utils/ApiModule.kt
  app/src/main/java/com/example/teumteum/utils/AuthIntercepter.kt
  app/src/main/java/com/example/teumteum/utils/NetworkModule.kt
Labels: 🐛fix

#190 [FEAT/#188] 틈 요청 플로우 종료 후 스택 정리
  app/src/main/java/com/example/teumteum/ui/friend/FriendSendFragment.kt
Labels: ✨feature

#189 [Refactor/#186] 토스트 메세지 제거, 피드 더미데이터, 온보딩 반복일정 수정
  app/src/main/java/com/example/teumteum/data/remote/alarm/AlarmService.kt
  app/src/main/java/com/example/teumteum/ui/alarm/AlarmFragment.kt
  app/src/main/java/com/example/teumteum/ui/calendar/MonthlyCalendarFragment.kt
  app/src/main/java/com/example/teumteum/ui/calendar/WeeklyCalendarFragment.kt
  app/src/main/java/com/example/teumteum/ui/feed/ContentsHorizontalAdapter.kt
  app/src/main/java/com/example/teumteum/ui/feed/FeedContentAdapter.kt
  app/src/main/java/com/example/teumteum/ui/feed/FeedContentFragment.kt
  app/src/main/java/com/example/teumteum/ui/feed/FeedFragment.kt
  app/src/main/java/com/example/teumteum/ui/feed/data/Contents.kt
  app/src/main/java/com/example/teumteum/ui/feed/data/Feed.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend01SearchResultFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02AcceptBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02PossibleTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RejectBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RequestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02ResponseFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02SuggestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendMatchingPreviewDialog.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowingFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendPromiseFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateFriendAddFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateMatchingDetailFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/PromiseDetailBottomSheet.kt
  app/src/main/java/com/example/teumteum/ui/friend/SharedTeumTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/main/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/signin/LoginActivity.kt
  app/src/main/java/com/example/teumteum/ui/signup/AgreementFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/BottomSheetScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingNicknameFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingProfileFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingSleepPatternFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishSetting02Fragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishSetting03Fragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistFragment.kt
  app/src/main/res/drawable/content_apple_new_features.png
  app/src/main/res/drawable/content_car_wash.png
  app/src/main/res/drawable/content_designer_communication.png
  app/src/main/res/drawable/content_development_glossary.png
  app/src/main/res/drawable/content_global_warming.png
  app/src/main/res/drawable/content_jini.png
  app/src/main/res/drawable/profile_apple.png
  app/src/main/res/drawable/profile_gyeoli.png
  app/src/main/res/drawable/profile_habit.png
  app/src/main/res/drawable/profile_jini.png
  app/src/main/res/drawable/profile_minary.png
  app/src/main/res/drawable/profile_naru.png
Labels: ♻️refactor, 👽우진👽

#183 [Feat/#158] 빈틈 채우기 api 연동
  app/src/main/java/com/example/teumteum/data/remote/activity/model/ActivityRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/activity/model/ActivityResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/activity/repository/ActivityRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/activity/service/ActivityService.kt
  app/src/main/java/com/example/teumteum/data/remote/wish/model/WishRequest.kt
  app/src/main/java/com/example/teumteum/data/remote/wish/repository/WishRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/wish/service/WishService.kt
  app/src/main/java/com/example/teumteum/ui/activity/FillingSetting01Fragment.kt
  app/src/main/java/com/example/teumteum/ui/activity/FillingSetting02Fragment.kt
  app/src/main/java/com/example/teumteum/ui/activity/FillingSetting03Fragment.kt
  app/src/main/java/com/example/teumteum/ui/activity/adapter/AiRecommendRVAdapter.kt
  app/src/main/java/com/example/teumteum/ui/activity/adapter/WishRecommendRVAdapter.kt
  app/src/main/java/com/example/teumteum/ui/activity/viewModel/ActivityViewModel.kt
  app/src/main/java/com/example/teumteum/ui/main/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/TodoRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/todo/viewModel/TodoViewModel.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishRegisterFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishSetting01Fragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishSetting02Fragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishSetting03Fragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishlistEditFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/adapter/WishlistRVAdapter.kt
  app/src/main/java/com/example/teumteum/ui/wish/viewModel/WishViewModel.kt
  app/src/main/res/layout/dialog_confirm_register.xml
  app/src/main/res/layout/fragment_filling_setting_01.xml
  app/src/main/res/layout/fragment_filling_setting_02.xml
  app/src/main/res/layout/fragment_filling_setting_03.xml
  app/src/main/res/layout/fragment_wish_setting_01.xml
  app/src/main/res/layout/fragment_wish_setting_02.xml
  app/src/main/res/layout/fragment_wish_setting_03.xml
Labels: ✨feature, 😺승현😺

#202 [FIX/#176] 친구 목록 및 프로필 즐겨찾기 상태 표시 로직 수정
  app/src/main/java/com/example/teumteum/data/remote/friend/model/FollowingResult.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowingFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
Labels: 🐛fix

#204 [FEAT/#203] 로그아웃 API 연동
  app/src/main/java/com/example/teumteum/data/remote/login/service/AuthService.kt
  app/src/main/java/com/example/teumteum/ui/myhome/MyAccountSettingFragment.kt
  app/src/main/java/com/example/teumteum/utils/LogoutManager.kt
  app/src/main/java/com/example/teumteum/utils/NetworkModule.kt
Labels: ✨feature

#211 [Fix/#210] 오늘의 틈 요청 가능하도록 수정
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateDateFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateMatchingDetailFragment.kt
Labels: 🐛fix

#206 [FEAT/#205] 틈메이트 제외 토글 및 가능한 시간 재조회 기능 추가
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/FriendProfileAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
  app/src/main/res/drawable/eyes_off.xml
  app/src/main/res/layout/fragment_friend_roommate_time.xml
  app/src/main/res/layout/item_friend_profile_card.xml
Labels: ✨feature

#220 [Feat/#216] FCM 토큰 등록/비활성화 API 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teumteum/application/MyFirebaseMessagingService.kt
  app/src/main/java/com/example/teumteum/data/remote/alarm/FcmRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/alarm/FcmService.kt
  app/src/main/java/com/example/teumteum/data/remote/alarm/FcmTokenStore.kt
  app/src/main/java/com/example/teumteum/data/remote/alarm/dto/FcmToken.kt
  app/src/main/java/com/example/teumteum/data/remote/login/LogoutManager.kt
  app/src/main/java/com/example/teumteum/data/remote/login/LogoutUseCase.kt
  app/src/main/java/com/example/teumteum/ui/main/MainActivity.kt
  app/src/main/java/com/example/teumteum/ui/myhome/MyAccountSettingFragment.kt
  app/src/main/java/com/example/teumteum/ui/signin/viewModel/LoginViewModel.kt
  app/src/main/java/com/example/teumteum/utils/ApiModule.kt
  app/src/main/java/com/example/teumteum/utils/AuthIntercepter.kt
  app/src/main/java/com/example/teumteum/utils/NotificationHelper.kt
  settings.gradle.kts
Labels: ✨feature

#214 [BUG/#213] 팔로우 관련 문제
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowFragment.kt
Labels: 🐛fix, 🐰희원🐰

#224 [Refactor/#223] 원형시간표 스와이프 변경 적용
  app/src/main/java/com/example/teumteum/ui/activity/FillingSetting01Fragment.kt
  app/src/main/java/com/example/teumteum/ui/clock/ClockVPAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/main/HomeFragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishSetting01Fragment.kt
  app/src/main/res/layout/fragment_filling_setting_01.xml
  app/src/main/res/layout/fragment_friend_roommate_time.xml
  app/src/main/res/layout/fragment_wish_setting_01.xml
  app/src/main/res/layout/item_clock_mini_page.xml
Labels: ♻️refactor, 👽우진👽

#227 [Fix/#226] 재요청 시 요청카드 뷰페이저 문제
  app/src/main/java/com/example/teumteum/ui/friend/Friend02AcceptBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02PossibleTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RejectBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RequestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/adapter/TeumReceivedAdapter.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
  app/src/main/res/layout/fragment_friend02_suggest.xml
Labels: 🐛fix, 👽우진👽

#234 [Feat/#233] 친구 목록 무한스크롤 및 공통 PagingResponse 적용
  app/src/main/java/com/example/teumteum/data/remote/friend/model/FollowerResult.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/FollowingPageResult.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/model/PagingResponse.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/repository/FriendRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/friend/service/FriendService.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
Labels: ✨feature, ♻️refactor

#232 [FIX/#231] 자동 로그인 로직 개선
  app/src/main/java/com/example/teumteum/ui/signin/LoginActivity.kt
  app/src/main/java/com/example/teumteum/ui/signup/CompleteFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingNicknameFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/SignUpActivity.kt
  app/src/main/java/com/example/teumteum/ui/splash/SplashActivity.kt
Labels: 🐛fix

#230 [Fix/#229] 토큰 재발급/로그아웃 처리의 안정화
  app/src/main/java/com/example/teumteum/utils/AuthIntercepter.kt
  app/src/main/java/com/example/teumteum/utils/RefreshSingleFlight.kt
Labels: ♻️refactor, 🐛fix

#241 [Refactor/#221] 시간 유효성 검사 작업
  app/src/main/java/com/example/teumteum/ui/activity/FillingSetting02Fragment.kt
  app/src/main/java/com/example/teumteum/ui/activity/FillingSetting03Fragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishSetting02Fragment.kt
  app/src/main/java/com/example/teumteum/ui/wish/WishSetting03Fragment.kt
Labels: ♻️refactor, 😺승현😺

#255 [FIX/#254] 위시리스트 없을 때 레이아웃 제약 수정
  app/src/main/res/layout/fragment_wishlist.xml
Labels: 🐛fix

#264 [FIX/#263] 공개투두 RecyclerView 스크롤 안 되는 문제 해결
  app/src/main/res/layout/fragment_friend_todo_list.xml
Labels: 🐛fix, 🐨지애🐨

#266 [Refactor/#265] 색상 코드 통일
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/dialog_friend_matching_preview.xml
  app/src/main/res/layout/fragment_agreement.xml
  app/src/main/res/layout/fragment_bottom_sheet_schedule.xml
  app/src/main/res/layout/fragment_complete.xml
  app/src/main/res/layout/fragment_friend02_possible_time.xml
  app/src/main/res/layout/fragment_friend02_request.xml
  app/src/main/res/layout/fragment_friend02_response.xml
  app/src/main/res/layout/fragment_friend_profile_follow.xml
  app/src/main/res/layout/fragment_friend_profile_following.xml
  app/src/main/res/layout/fragment_friend_reject_send.xml
  app/src/main/res/layout/fragment_friend_roommate_matching_detail.xml
  app/src/main/res/layout/fragment_friend_send.xml
  app/src/main/res/layout/fragment_my_home.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/layout/fragment_on_boarding_nickname.xml
  app/src/main/res/layout/fragment_on_boarding_profile.xml
  app/src/main/res/layout/fragment_on_boarding_remind.xml
  app/src/main/res/layout/fragment_on_boarding_schedule.xml
  app/src/main/res/layout/fragment_on_boarding_sleep_pattern.xml
  app/src/main/res/layout/fragment_terms_detail.xml
Labels: ♻️refactor, 😺승현😺

#268 [FEAT/#267] 마이페이지 일정에 투두리스트 api 사용
  app/src/main/java/com/example/teumteum/data/remote/friend/repository/FriendRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/mypage/repository/MyPageRepository.kt
  app/src/main/java/com/example/teumteum/data/remote/mypage/service/MyPageService.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend01SearchResultFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02PossibleTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RejectBottomSheetFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02RequestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/Friend02SuggestFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendMatchingPreviewDialog.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendProfileFollowingFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateDateFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateFriendAddFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateFriendFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/FriendRoommateMatchingDetailFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/PromiseDetailBottomSheet.kt
  app/src/main/java/com/example/teumteum/ui/friend/SharedTeumTimeFragment.kt
  app/src/main/java/com/example/teumteum/ui/friend/viewModel/FriendViewModel.kt
  app/src/main/java/com/example/teumteum/ui/myhome/MyProfileFragment.kt
  app/src/main/java/com/example/teumteum/ui/myhome/viewModel/MyHomeViewModel.kt
  app/src/main/java/com/example/teumteum/ui/signup/AgreementFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingNicknameFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingScheduleFragment.kt
  app/src/main/java/com/example/teumteum/ui/signup/OnBoardingSleepPatternFragment.kt
Labels: ✨feature, 😺승현😺
